app:
  behaviour:
    # number of words in run
    words: 10
    # number of right answers per word (after which word changes its status to 'learned')
    answers: 10

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  h2: # just in case -- no console in app
    console:
      path: /h2-console
      settings:
        web-allow-others: false
  jpa: # temporary generate schema from JPA markup
    generate-ddl: true
    hibernate:
      ddl-auto: create