app:
  loader:
    enabled: false
  tutor:
    run:
      # number of words in run
      words: 10
      # number of right answers per word (after which word changes its status to 'learned')
      answers: 10

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    username: dev
    password: dev
    initialization-mode: never
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
